メール重複チェック
monmun810/ex-emp-management-bugfix pull request #29
Opened 2024-06-08 06:41 UTC by monmun018

メール重複チェックを非同期処理で実装した。
#5

2024-06-10 01:26 UTC, igamasayuki reviewed
気になる点を下にコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)


　jQuery+Ajaxを使用した場合でも、登録ボタンを押された際に
　サーバー側でもチェックを行うようにしてください。
　(jQuery+Ajaxを使用していても良いですが、必ずサーバー側でもチェックが必要です。
　理由：ブラウザでJavaScriptを無効にしていた場合でもチェックできるため)

2024-06-10 01:27 UTC, igamasayuki requested changes
気になる点を下にコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

　jQuery+Ajaxを使用した場合でも、登録ボタンを押された際に
　サーバー側でもチェックを行うようにしてください。
　(jQuery+Ajaxを使用していても良いですが、必ずサーバー側でもチェックが必要です。
　理由：ブラウザでJavaScriptを無効にしていた場合でもチェックできるため)

2024-06-10 07:02 UTC, monmun018 commented
サーバー側で対応しました！レビューをよろしくお願いいたします。

2024-06-10 08:43 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-10 08:43 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
>  			model.addAttribute("insertAdministratorForm", form);
これは勝手に行われるため必要ありません。

2024-06-10 08:54 UTC, monmun018 commented on src/main/java/com/example/controller/AdministratorController.java
>  			model.addAttribute("insertAdministratorForm", form);
モデルスコープのご指摘をありがとうございます。

2024-06-11 01:38 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-11 01:39 UTC, merged